// <auto-generated />
using CIDM3312_Star_Wars.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIDM3312_Star_Wars.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230504011203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CIDM3312_Star_Wars.Models.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattlePoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterID");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("CIDM3312_Star_Wars.Models.CharacterWeapon", b =>
                {
                    b.Property<int>("CharacterID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterID", "WeaponID");

                    b.HasIndex("WeaponID");

                    b.ToTable("CharacterWeapon");
                });

            modelBuilder.Entity("CIDM3312_Star_Wars.Models.Classification", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Allegiance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterID1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subclass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterID");

                    b.HasIndex("CharacterID1");

                    b.ToTable("Classification");
                });

            modelBuilder.Entity("CIDM3312_Star_Wars.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaponDamage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WeaponID");

                    b.ToTable("Weapon");
                });

            modelBuilder.Entity("CIDM3312_Star_Wars.Models.CharacterWeapon", b =>
                {
                    b.HasOne("CIDM3312_Star_Wars.Models.Character", "Character")
                        .WithMany("CharacterWeapons")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIDM3312_Star_Wars.Models.Weapon", "Weapon")
                        .WithMany("CharacterWeapons")
                        .HasForeignKey("WeaponID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("CIDM3312_Star_Wars.Models.Classification", b =>
                {
                    b.HasOne("CIDM3312_Star_Wars.Models.Character", "Character")
                        .WithMany("Classifications")
                        .HasForeignKey("CharacterID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("CIDM3312_Star_Wars.Models.Character", b =>
                {
                    b.Navigation("CharacterWeapons");

                    b.Navigation("Classifications");
                });

            modelBuilder.Entity("CIDM3312_Star_Wars.Models.Weapon", b =>
                {
                    b.Navigation("CharacterWeapons");
                });
#pragma warning restore 612, 618
        }
    }
}
