using Microsoft.EntityFrameworkCore;

namespace CIDM3312_Star_Wars.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new Context(serviceProvider.GetRequiredService<DbContextOptions<Context>>()))
            {
                if (context.Character.Any())
                {
                    return;
                }

                List<Character> characters = new List<Character> {
                    new Character {Name = "Luke Skywalker", Health = 750, BattlePoints = 4000, Class = "Hero", Subclass = "Jedi", Allegiance = "Rebel Alliance"},
                    new Character {Name = "Leia Organa", Health = 650, BattlePoints = 4000, Class = "Hero", Subclass = "Rebel", Allegiance = "Rebel Alliance"},
                    new Character {Name = "Han Solo", Health = 650, BattlePoints = 4000, Class = "Hero", Subclass = "Scoundrel", Allegiance = "Rebel Alliance"},
                    new Character {Name = "Chewbacca", Health = 700, BattlePoints = 4000, Class = "Hero", Subclass = "Scoundrel", Allegiance = "Rebel Alliance"},
                    new Character {Name = "Lando Calrissian", Health = 650, BattlePoints = 4000, Class = "Hero", Subclass = "Scoundrel", Allegiance = "Rebel Alliance"},
                    new Character {Name = "Yoda", Health = 700, BattlePoints = 4000, Class = "Hero", Subclass = "Jedi", Allegiance = "Galactic Republic"},
                    new Character {Name = "Rey", Health = 750, BattlePoints = 4000, Class = "Hero", Subclass = "Jedi", Allegiance = "Resistance"},
                    new Character {Name = "Finn", Health = 600, BattlePoints = 4000, Class = "Hero", Subclass = "Support", Allegiance = "Resistance"},
                    new Character {Name = "Obi-Wan Kenobi", Health = 750, BattlePoints = 4000, Class = "Hero", Subclass = "Jedi", Allegiance = "Galactic Republic"},
                    new Character {Name = "Anakin Skywalker", Health = 800, BattlePoints = 4000, Class = "Hero", Subclass = "Jedi", Allegiance = "Galactic Republic"},
                    new Character {Name = "BB-8", Health = 650, BattlePoints = 4000, Class = "Hero", Subclass = "Droid", Allegiance = "Resistance"},
                    new Character {Name = "Darth Vader", Health = 800, BattlePoints = 4000, Class = "Hero", Subclass = "Sith", Allegiance = "Galactic Empire"},
                    new Character {Name = "Emperor Palpatine", Health = 700, BattlePoints = 4000, Class = "Hero", Subclass = "Sith", Allegiance = "Galactic Empire"},
                    new Character {Name = "Boba Fett", Health = 600, BattlePoints = 4000, Class = "Hero", Subclass = "Bounty Hunter", Allegiance = "Galactic Empire"},
                    new Character {Name = "Bossk", Health = 600, BattlePoints = 4000, Class = "Hero", Subclass = "Bounty Hunter", Allegiance = "Galactic Empire"},
                    new Character {Name = "Iden Versio", Health = 650, BattlePoints = 4000, Class = "Hero", Subclass = "Commander", Allegiance = "Galactic Empire"},
                    new Character {Name = "Darth Maul", Health = 700, BattlePoints = 4000, Class = "Hero", Subclass = "Sith", Allegiance = "Separatists"},
                    new Character {Name = "Kylo Ren", Health = 750, BattlePoints = 4000, Class = "Hero", Subclass = "Sith", Allegiance = "First Order"},
                    new Character {Name = "Captain Phasma", Health = 700, BattlePoints = 4000, Class = "Hero", Subclass = "Captain", Allegiance = "First Order"},
                    new Character {Name = "General Grievous", Health = 800, BattlePoints = 4000, Class = "Hero", Subclass = "Droid", Allegiance = "Separatists"},
                    new Character {Name = "Count Dooku", Health = 750, BattlePoints = 4000, Class = "Hero", Subclass = "Sith", Allegiance = "Separatists"},
                    new Character {Name = "BB-9E", Health = 600, BattlePoints = 4000, Class = "Hero", Subclass = "Droid", Allegiance = "First Order"},
                    new Character {Name = "Assault Trooper", Health = 150, BattlePoints = 0, Class = "Primary", Subclass = "Assault", Allegiance = "All"},
                    new Character {Name = "Heavy Trooper", Health = 200, BattlePoints = 0, Class = "Primary", Subclass = "Heavy", Allegiance = "All"},
                    new Character {Name = "Officer Trooper", Health = 150, BattlePoints = 0, Class = "Primary", Subclass = "Officer", Allegiance = "All"},
                    new Character {Name = "Specialist Trooper", Health = 150, BattlePoints = 0, Class = "Primary", Subclass = "Specialist", Allegiance = "All"},
                    new Character {Name = "Wookie Warrior", Health = 320, BattlePoints = 1500, Class ="Reinforcement", Subclass = "Enforcer", Allegiance = "Galactic Republic"},
                    new Character {Name = "Clone Commando", Health = 350, BattlePoints = 2000, Class = "Reinforcement", Subclass = "Enforcer", Allegiance = "Galactic Republic"},
                    new Character {Name = "B2 Super Battle Droid", Health = 300, BattlePoints = 1500, Class = "Reinforcement", Subclass = "Enforcer", Allegiance = "Separatists"},
                    new Character {Name = "Droideka", Health = 350, BattlePoints = 1000, Class = "Reinforcement", Subclass = "Enforcer", Allegiance = "Separatists"},
                    new Character {Name = "Wookie Chief", Health = 320, BattlePoints = 1500, Class = "Reinforcement", Subclass = "Enforcer", Allegiance = "Rebel Alliance"},
                    new Character {Name = "Death Trooper", Health = 320, BattlePoints = 1500, Class = "Reinforcement", Subclass = "Enforcer", Allegiance = "Galactic Empire"},
                    new Character {Name = "Ovissian Gunner", Health = 320, BattlePoints = 2000, Class = "Reinforcement", Subclass = "Enforcer", Allegiance = "Resistance"},
                    new Character {Name = "First Order Flametrooper", Health = 400, BattlePoints = 1500, Class = "Reinforcement", Subclass = "Enforcer", Allegiance = "First Order"},
                    new Character {Name = "ARC Trooper", Health = 350, BattlePoints = 2000, Class = "Reinforcement", Subclass = "Infiltrator", Allegiance = "Galactic Republic"},
                    new Character {Name = "Commando Droid", Health = 350, BattlePoints = 2000, Class = "Reinforcement", Subclass = "Infiltrator", Allegiance = "Separatists"},
                    new Character {Name = "Caphex Spy", Health = 350, BattlePoints = 2000, Class = "Reinforcement", Subclass = "Infiltrator", Allegiance = "Resistance"},
                    new Character {Name = "Sith Trooper", Health = 350, BattlePoints = 1500, Class = "Reinforcement", Subclass = "Infiltrator", Allegiance = "First Order"},
                    new Character {Name = "Ewok Hunter", Health = 250, BattlePoints = 1500, Class = "Reinforcement", Subclass = "Infiltrator", Allegiance = "Rebel Alliance"},
                    new Character {Name = "ISB Agent", Health = 350, BattlePoints = 2000, Class = "Reinforcement", Subclass = "Infiltrator", Allegiance = "Galactic Empire"},
                    new Character {Name = "Jet Trooper", Health = 200, BattlePoints = 1000, Class = "Reinforcement", Subclass = "Aerial", Allegiance = "Galactic Republic"},
                    new Character {Name = "B2-RP Rocket Droid", Health = 200, BattlePoints = 1000, Class = "Reinforcement", Subclass = "Aerial", Allegiance = "Separatists"},
                    new Character {Name = "Rebel Rocket Jumper", Health = 200, BattlePoints = 1000, Class = "Reinforcement", Subclass = "Aerial", Allegiance = "Rebel Alliance"},
                    new Character {Name = "Imperial Rocket Trooper", Health = 200, BattlePoints = 1000, Class = "Reinforcement", Subclass = "Aerial", Allegiance = "Galactic Empire"},
                    new Character {Name = "Resistance Rocket-Jumper", Health = 200, BattlePoints = 1000, Class = "Reinforcement", Subclass = "Aerial", Allegiance = "Resistance"},
                    new Character {Name = "First Order Jet Trooper", Health = 200, BattlePoints = 1000, Class = "Reinforcement", Subclass = "Aerial", Allegiance = "First Order"}
                };
                context.AddRange(characters);

                List<Weapon> weapons = new List<Weapon> {
                    new Weapon {WeaponName = "Luke Skywalker's Lightsaber", WeaponDamage = 160-130},
                    new Weapon {WeaponName = "Leia”s E-11", WeaponDamage = 80-40},
                    new Weapon {WeaponName = "Han”s DL-44", WeaponDamage = 80-55},
                    new Weapon {WeaponName = "Bowcaster", WeaponDamage = 90-75},
                    new Weapon {WeaponName = "Lando”s X-8 Night Sniper", WeaponDamage = 40-25},
                    new Weapon {WeaponName = "Yoda”s Lightsaber", WeaponDamage = 150-125},
                    new Weapon {WeaponName = "Rey”s Lightsaber", WeaponDamage = 140-120},
                    new Weapon {WeaponName = "Finn”s EL-16", WeaponDamage = 52-45},
                    new Weapon {WeaponName = "Obi-Wan Kenobi's Lightsaber", WeaponDamage = 150-130},
                    new Weapon {WeaponName = "Anakin Skywalker's Lightsaber", WeaponDamage = 170-130},
                    new Weapon {WeaponName = "Shock Prod", WeaponDamage = 36-29},
                    new Weapon {WeaponName = "Darth Vader's Lightsaber", WeaponDamage = 160-130},
                    new Weapon {WeaponName = "Force Lightning", WeaponDamage = 28-14},
                    new Weapon {WeaponName = "EE-3 Blaster Rifle", WeaponDamage = 105-75},
                    new Weapon {WeaponName = "Bossk's Relby V-10", WeaponDamage = 126-45},
                    new Weapon {WeaponName = "Iden”s TL-50", WeaponDamage = 20-10},
                    new Weapon {WeaponName = "Darth Maul's Lightsaber", WeaponDamage = 150-120},
                    new Weapon {WeaponName = "Kylo Ren's Lightsaber", WeaponDamage = 165-125},
                    new Weapon {WeaponName = "Captain Phasma's Sonn-Blas F-11D", WeaponDamage = 19-15},
                    new Weapon {WeaponName = "Grevious' Lightsabers", WeaponDamage = 160-130},
                    new Weapon {WeaponName = "Count Dooku's Lightsaber", WeaponDamage = 160-130},
                    new Weapon {WeaponName = "A280", WeaponDamage = 33-19},
                    new Weapon {WeaponName = "A280C", WeaponDamage = 25-12},
                    new Weapon {WeaponName = "CR-2", WeaponDamage = 16-8},
                    new Weapon {WeaponName = "DC-15A", WeaponDamage = 36-19},
                    new Weapon {WeaponName = "E-5", WeaponDamage = 36-19},
                    new Weapon {WeaponName = "E-11", WeaponDamage = 35-15},
                    new Weapon {WeaponName = "E-11D", WeaponDamage = 35-20},
                    new Weapon {WeaponName = "EL-16", WeaponDamage = 36-19},
                    new Weapon {WeaponName = "EL-16HFE", WeaponDamage = 49-30},
                    new Weapon {WeaponName = "F-11D", WeaponDamage = 36-19},
                    new Weapon {WeaponName = "DC-15", WeaponDamage = 16-10},
                    new Weapon {WeaponName = "DC-15LE", WeaponDamage = 16-10},
                    new Weapon {WeaponName = "DLT-19", WeaponDamage = 17-13},
                    new Weapon {WeaponName = "E-5C", WeaponDamage = 16-10},
                    new Weapon {WeaponName = "FWMB-10", WeaponDamage = 16-10},
                    new Weapon {WeaponName = "FWMB-10K", WeaponDamage = 24-15},
                    new Weapon {WeaponName = "M-45", WeaponDamage = 16-10},
                    new Weapon {WeaponName = "RT-97C", WeaponDamage = 17-14},
                    new Weapon {WeaponName = "T-21", WeaponDamage = 50-34},
                    new Weapon {WeaponName = "TL-50", WeaponDamage = 15-11},
                    new Weapon {WeaponName = "Blurrg-1120", WeaponDamage = 30-12},
                    new Weapon {WeaponName = "DC-17", WeaponDamage = 34-17},
                    new Weapon {WeaponName = "DH-17", WeaponDamage = 25-5},
                    new Weapon {WeaponName = "DL-18", WeaponDamage = 41-15},
                    new Weapon {WeaponName = "Glie-44", WeaponDamage = 34-17},
                    new Weapon {WeaponName = "S-5", WeaponDamage = 67-45},
                    new Weapon {WeaponName = "RG-4D", WeaponDamage = 34-17},
                    new Weapon {WeaponName = "RK-3", WeaponDamage = 34-17},
                    new Weapon {WeaponName = "SE-44", WeaponDamage = 34-17},
                    new Weapon {WeaponName = "SE-44C", WeaponDamage = 31-15},
                    new Weapon {WeaponName = "A180 Sniper", WeaponDamage = 45},
                    new Weapon {WeaponName = "A280-CFE", WeaponDamage = 33-25},
                    new Weapon {WeaponName = "Cycler Rifle", WeaponDamage = 90},
                    new Weapon {WeaponName = "DLT-19D", WeaponDamage = 45},
                    new Weapon {WeaponName = "DLT-19X", WeaponDamage = 100-67},
                    new Weapon {WeaponName = "DLT-20A", WeaponDamage = 45},
                    new Weapon {WeaponName = "E-5s", WeaponDamage = 45},
                    new Weapon {WeaponName = "IQA-11", WeaponDamage = 67},
                    new Weapon {WeaponName = "NT-242", WeaponDamage = 106},
                    new Weapon {WeaponName = "Valken-38X", WeaponDamage = 45},
                    new Weapon {WeaponName = "DC-17m Repeating Blaster Rifle", WeaponDamage = 33-6},
                    new Weapon {WeaponName = "Twin Wrist Blaster", WeaponDamage = 43-24},
                    new Weapon {WeaponName = "Twin Blaster Cannons", WeaponDamage = 40-5},
                    new Weapon {WeaponName = "Modified Z-6B Rotary Cannon", WeaponDamage = 25-11},
                    new Weapon {WeaponName = "D-93 Incinerator", WeaponDamage = 22-11},
                    new Weapon {WeaponName = "Dual DC-17", WeaponDamage = 35-17},
                    new Weapon {WeaponName = "Modified GLIE-44", WeaponDamage = 70-45},
                    new Weapon {WeaponName = "ST-W48", WeaponDamage = 24-12},
                    new Weapon {WeaponName = "Hunter's Bow", WeaponDamage = 49},
                    new Weapon {WeaponName = "Dual RK-3", WeaponDamage = 29-17},
                    new Weapon {WeaponName = "G125 Projectile Launcher", WeaponDamage = 20-5}

                };
                context.AddRange(weapons);

                List<CharacterWeapon> tools = new List<CharacterWeapon> {
                    new CharacterWeapon {CharacterID = 1, WeaponID = 1},
                    new CharacterWeapon {CharacterID = 2, WeaponID = 2},
                    new CharacterWeapon {CharacterID = 3, WeaponID = 3},
                    new CharacterWeapon {CharacterID = 4, WeaponID = 4},
                    new CharacterWeapon {CharacterID = 5, WeaponID = 5},
                    new CharacterWeapon {CharacterID = 6, WeaponID = 6},
                    new CharacterWeapon {CharacterID = 7, WeaponID = 7},
                    new CharacterWeapon {CharacterID = 8, WeaponID = 8},
                    new CharacterWeapon {CharacterID = 9, WeaponID = 9},
                    new CharacterWeapon {CharacterID = 10, WeaponID = 10},
                    new CharacterWeapon {CharacterID = 11, WeaponID = 11},
                    new CharacterWeapon {CharacterID = 12, WeaponID = 12},
                    new CharacterWeapon {CharacterID = 13, WeaponID = 13},
                    new CharacterWeapon {CharacterID = 14, WeaponID = 14},
                    new CharacterWeapon {CharacterID = 15, WeaponID = 15},
                    new CharacterWeapon {CharacterID = 16, WeaponID = 16},
                    new CharacterWeapon {CharacterID = 17, WeaponID = 17},
                    new CharacterWeapon {CharacterID = 18, WeaponID = 18},
                    new CharacterWeapon {CharacterID = 19, WeaponID = 19},
                    new CharacterWeapon {CharacterID = 20, WeaponID = 20},
                    new CharacterWeapon {CharacterID = 21, WeaponID = 21},
                    new CharacterWeapon {CharacterID = 22, WeaponID = 11},
                    new CharacterWeapon {CharacterID = 23, WeaponID = 22},
                    new CharacterWeapon {CharacterID = 23, WeaponID = 23},
                    new CharacterWeapon {CharacterID = 23, WeaponID = 24},
                    new CharacterWeapon {CharacterID = 23, WeaponID = 25},
                    new CharacterWeapon {CharacterID = 23, WeaponID = 26},
                    new CharacterWeapon {CharacterID = 23, WeaponID = 27},
                    new CharacterWeapon {CharacterID = 23, WeaponID = 28},
                    new CharacterWeapon {CharacterID = 23, WeaponID = 29},
                    new CharacterWeapon {CharacterID = 23, WeaponID = 30},
                    new CharacterWeapon {CharacterID = 23, WeaponID = 31},
                    new CharacterWeapon {CharacterID = 24, WeaponID = 32},
                    new CharacterWeapon {CharacterID = 24, WeaponID = 33},
                    new CharacterWeapon {CharacterID = 24, WeaponID = 34},
                    new CharacterWeapon {CharacterID = 24, WeaponID = 35},
                    new CharacterWeapon {CharacterID = 24, WeaponID = 36},
                    new CharacterWeapon {CharacterID = 24, WeaponID = 37},
                    new CharacterWeapon {CharacterID = 24, WeaponID = 38},
                    new CharacterWeapon {CharacterID = 24, WeaponID = 39},
                    new CharacterWeapon {CharacterID = 24, WeaponID = 40},
                    new CharacterWeapon {CharacterID = 24, WeaponID = 41},
                    new CharacterWeapon {CharacterID = 25, WeaponID = 42},
                    new CharacterWeapon {CharacterID = 25, WeaponID = 43},
                    new CharacterWeapon {CharacterID = 25, WeaponID = 44},
                    new CharacterWeapon {CharacterID = 25, WeaponID = 45},
                    new CharacterWeapon {CharacterID = 25, WeaponID = 46},
                    new CharacterWeapon {CharacterID = 25, WeaponID = 47},
                    new CharacterWeapon {CharacterID = 25, WeaponID = 48},
                    new CharacterWeapon {CharacterID = 25, WeaponID = 49},
                    new CharacterWeapon {CharacterID = 25, WeaponID = 50},
                    new CharacterWeapon {CharacterID = 25, WeaponID = 51},
                    new CharacterWeapon {CharacterID = 26, WeaponID = 52},
                    new CharacterWeapon {CharacterID = 26, WeaponID = 53},
                    new CharacterWeapon {CharacterID = 26, WeaponID = 54},
                    new CharacterWeapon {CharacterID = 26, WeaponID = 55},
                    new CharacterWeapon {CharacterID = 26, WeaponID = 56},
                    new CharacterWeapon {CharacterID = 26, WeaponID = 57},
                    new CharacterWeapon {CharacterID = 26, WeaponID = 58},
                    new CharacterWeapon {CharacterID = 26, WeaponID = 59},
                    new CharacterWeapon {CharacterID = 26, WeaponID = 60},
                    new CharacterWeapon {CharacterID = 26, WeaponID = 61},
                    new CharacterWeapon {CharacterID = 27, WeaponID = 4},
                    new CharacterWeapon {CharacterID = 28, WeaponID = 62},
                    new CharacterWeapon {CharacterID = 29, WeaponID = 63},
                    new CharacterWeapon {CharacterID = 30, WeaponID = 64},
                    new CharacterWeapon {CharacterID = 31, WeaponID = 4},
                    new CharacterWeapon {CharacterID = 32, WeaponID = 28},
                    new CharacterWeapon {CharacterID = 33, WeaponID = 65},
                    new CharacterWeapon {CharacterID = 34, WeaponID = 66},
                    new CharacterWeapon {CharacterID = 35, WeaponID = 67},
                    new CharacterWeapon {CharacterID = 36, WeaponID = 26},
                    new CharacterWeapon {CharacterID = 37, WeaponID = 68},
                    new CharacterWeapon {CharacterID = 38, WeaponID = 69},
                    new CharacterWeapon {CharacterID = 39, WeaponID = 70},
                    new CharacterWeapon {CharacterID = 40, WeaponID = 71},
                    new CharacterWeapon {CharacterID = 41, WeaponID = 43},
                    new CharacterWeapon {CharacterID = 42, WeaponID = 63},
                    new CharacterWeapon {CharacterID = 43, WeaponID = 23},
                    new CharacterWeapon {CharacterID = 44, WeaponID = 27},
                    new CharacterWeapon {CharacterID = 45, WeaponID = 30},
                    new CharacterWeapon {CharacterID = 46, WeaponID = 72}
                };
                context.AddRange(tools);

                context.SaveChanges();
            }
        }
    }
}